= Redis SQL
:linkattrs:
:project-owner:   redis-field-engineering
:project-name:    redis-sql
:project-group:   com.redis
:project-version: 0.2.1
:artifact-id:     trino-redisearch
:codecov-token:   CQFF495IPH

image:https://github.com/{project-owner}/{project-name}/actions/workflows/early-access.yml/badge.svg["Build Status", link="https://github.com/{project-owner}/{project-name}/actions/workflows/early-access.yml"]
image:https://img.shields.io/maven-central/v/{project-group}/{artifact-id}[Download, link="https://search.maven.org/#search|ga|1|{artifact-id}"]
image:https://img.shields.io/nexus/s/{project-group}/{artifact-id}?server=https%3A%2F%2Fs01.oss.sonatype.org[Snapshot,link="https://s01.oss.sonatype.org/#nexus-search;quick~{artifact-id}"]
image:https://codecov.io/gh/{project-owner}/{project-name}/branch/master/graph/badge.svg?token={codecov-token}["Coverage", link="https://codecov.io/gh/{project-owner}/{project-name}"]

Redis SQL is a SQL interface to https://oss.redislabs.com/redisearch/[RediSearch] implemented as a https://trino.io[Trino] connector.
It allows the use of RediSearch indexes as tables in Trino.

== Requirements

To connect to RediSearch you need:

. RediSearch 2.0 or higher
. Network access from the Trino coordinator and workers to RediSearch.

== Configuration

To configure the RediSearch connector, create a catalog properties file `etc/catalog/redisearch.properties` with the following contents (replace properties as appropriate):

[source,properties]
----
connector.name=redisearch
redisearch.uri=redis://user:pass@host:6379
----

=== Configuration Properties

`redisearch.uri`:: A connection string containing the protocol, credential, and host info to connect to Redis.
+
For example, the connection string may use the format `redis://<user>:<pass>@<host>:<port>`.
+
See the https://github.com/lettuce-io/lettuce-core/wiki/Redis-URI-and-connection-details#uri-syntax[Redis URI syntax] for more information.
+
This property is required and has no default. A Redis URI must be provided to connect to RediSearch.

`redisearch.case-insensitive-name-matching`:: Match index names case insensitively.
+
This property is optional and the default is `false`.

`redisearch.default-limit`:: Max number of documents returned by FT.SEARCH and FT.AGGREGATE when no limit is present in the SQL query.
+
This property is optional and the default is `10000`.


== Docker Example

1. Launch the containers
+
[source,console]
----
docker-compose up
----

2. Create a RediSearch index
+
[source,console]
----
docker exec redismod /usr/local/bin/redis-cli FT.CREATE beers ON HASH PREFIX 1 beer: SCHEMA id TAG SORTABLE brewery_id TAG SORTABLE name TEXT SORTABLE abv NUMERIC SORTABLE descript TEXT style_name TAG SORTABLE cat_name TAG SORTABLE
----

3. Add documents to the index
+
[source,console]
----
docker run --add-host=host.docker.internal:host-gateway jruaux/riot-file -h host.docker.internal import https://storage.googleapis.com/jrx/beers.json hset --keyspace beer --keys id
----

4. Run the Trino CLI
+
[source,console]
----
docker exec -it trino trino --catalog redisearch --schema default
----

5. Run a SQL query
+
[source,console]
----
trino:default> select * from beers;
----

== Install and Run

=== Install Trino

https://trino.io/docs/current/installation.html

For macOS: `brew install trino`

=== Install the connector

1. Download latest https://github.com/redis-field-engineering/{project-name}/releases/latest[release].

2. Unzip the release without any directory structure under `<trino>/plugin/redisearch`:
+
[source,console,subs="verbatim,attributes"]
----
unzip -j trino-redisearch-{project-version}.zip -d /opt/trino/plugin/redisearch
----

3. Create a `redisearch.properties` file under `<trino>/etc/catalog` directory:
+
.redisearch.properties
[source,properties]
----
connector.name=redisearch
redisearch.uri=redis://localhost:6379
----

=== Run

1. Start Trino server:
+
[source,console]
----
`trino-server start`
----

2. Connect to Trino using the CLI:
+
[source,console]
----
`trino --catalog redisearch --schema default`
----

3. Run a SQL query:
+
[source,console]
----
trino:default> select count(*) from myIdx;
----

== Tableau

Follow these steps to connect Tableau: https://help.tableau.com/current/pro/desktop/en-us/examples_presto.htm

== Build

Run these commands to build the Trino connector for RediSearch from source:

[source,console]
----
git clone https://github.com/redis-field-engineering/redis-sql.git
cd redis-sql
./gradlew clean build
----
